import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppToaster from "@/components/AppToaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: `
          (function() {
            try {
              var theme = localStorage.getItem('theme');
              if (theme !== 'light' && theme !== 'dark') {
                theme = 'light';
                localStorage.setItem('theme', 'light');
              }
              var isDark = theme === 'dark';
              if (isDark) {
                document.documentElement.classList.add('dark');
              } else {
                document.documentElement.classList.remove('dark');
              }
            } catch (e) {}
          })()
        `}} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppToaster />
        <div className="flex min-h-screen">
          <div className="flex flex-col flex-1">
            <main className="flex-1">{children}</main>
            
          </div>
        </div>
      </body>
    </html>
  );
}
